### ISSUE TITLE
Paginated responses

### ISSUE THREAD

**Issue by Oshuma** [ammoready/gun_broker#4]
http://api.sandbox.gunbroker.com/User/HelpObjects/PagingParameters

Ideally, the `#all` methods should return **all** entries (making multiple requests if necessary), but should also accept an optional `PageSize` param.

**Comment by jeffdill2** [comment]
@Oshuma ha! I didn't realize we had an issue for this either. 😂 

I actually pushed out this functionality back in May.

**Comment by Oshuma** [comment]
Hah, nice.
