### ISSUE TITLE
Order related endpoints

### ISSUE THREAD

**Issue by Oshuma** [ammoready/gun_broker#6]
- [ ] `/SoldOrders [GET]` - http://api.gunbroker.com/User/Help/OrdersSold
- [ ] `/Orders/{orderID} [GET]` - http://api.gunbroker.com/User/Help/OrdersGet
- [ ] `/Orders/{orderID}/Flags [PUT]` - http://api.gunbroker.com/User/Help/OrdersFlagsPut

**Comment by jeffdill2** [comment]
@Oshuma just realized you had an open issue for this, going back to over 3 years ago. 😆 

Orders stuff is built now. I'm going to test/tweak today and it'll go out next week.

**Comment by Oshuma** [comment]
Well, I'm glad my issues are still relevant all these years later.  ;)

**Comment by jeffdill2** [comment]
Lasting impact. 🙌
